language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
    - functions/node_modules
    - gui/node_modules
script:
  - npm test
  - npm run build
after_success:
  - ./travis-deploy.sh
